const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const MONTHS=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const defaultState={year:new Date().getFullYear(),month:new Date().getMonth(),patternKey:localStorage.getItem("patternKey")||"dnvv",customPattern:JSON.parse(localStorage.getItem("customPattern")||"[]"),cycleStart:localStorage.getItem("cycleStart")||new Date().toISOString().split("T")[0],offset:parseInt(localStorage.getItem("offset")||"0",10),themeMode:localStorage.getItem("themeMode")||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'),themePalette:localStorage.getItem("themePalette")||"blue"};let state={...defaultState};
function applyTheme(){document.body.classList.toggle("dark",state.themeMode==='dark');document.body.classList.toggle("light",state.themeMode==='light');document.documentElement.classList.remove("theme-blue","theme-green","theme-amber");document.documentElement.classList.add(`theme-${state.themePalette}`);if(state.themeMode==='dark'){$("#sunIcon").classList.remove("hidden");$("#moonIcon").classList.add("hidden");}else{$("#sunIcon").classList.add("hidden");$("#moonIcon").classList.remove("hidden");}}
applyTheme();
$("#themeToggle").addEventListener("click",()=>{state.themeMode=state.themeMode==='dark'?'light':'dark';localStorage.setItem("themeMode",state.themeMode);applyTheme();});
function setMonthLabel(){$("#monthLabel").textContent=`${MONTHS[state.month]} ${state.year}`;}
$("#prevMonth").addEventListener("click",()=>{state.month--;if(state.month<0){state.month=11;state.year--;}renderCalendar();});
$("#nextMonth").addEventListener("click",()=>{state.month++;if(state.month>11){state.month=0;state.year++;}renderCalendar();});
const BASE={dnvv:["Д","Н","В","В"],"2on2off":["Д","Д","В","В"],"5_2":["Д","Д","Д","Д","Д","В","В"]};
function patternArr(){return(state.patternKey==="custom"&&state.customPattern.length)?state.customPattern:(BASE[state.patternKey]||BASE.dnvv);}
function dayTypeFor(date){const p=patternArr();const start=new Date(state.cycleStart+"T00:00:00");const diff=Math.floor((date-start)/86400000);const idx=(diff+state.offset)%p.length;return p[(idx+p.length)%p.length];}
function mondayIdx(d){return(d.getDay()+6)%7;}
function renderCalendar(){const cal=$("#calendar");cal.innerHTML="";const y=state.year,m=state.month;const first=new Date(y,m,1);const daysInMonth=new Date(y,m+1,0).getDate();const today=new Date();const isThisMonth=today.getFullYear()===y&&today.getMonth()===m;setMonthLabel();const lead=mondayIdx(first);for(let i=0;i<lead;i++)cal.appendChild(document.createElement("div"));for(let d=1;d<=daysInMonth;d++){const date=new Date(y,m,d);const label=dayTypeFor(date);const cell=document.createElement("div");cell.className="cell";const num=document.createElement("div");num.className="num";num.textContent=d;const pill=document.createElement("div");pill.className="pill";pill.textContent=label;if(isThisMonth&&d===today.getDate())cell.classList.add("today");cell.appendChild(num);cell.appendChild(pill);cal.appendChild(cell);}}renderCalendar();
const menu=$("#bottomMenu"),scrim=$("#scrim"),edgeOpen=$("#edgeOpen");$("#menuToggle").addEventListener("click",()=>menu.classList.contains("open")?closeMenu():openMenu());scrim.addEventListener("click",closeMenu);
function openMenu(){menu.classList.add("open");menu.setAttribute("aria-hidden","false");scrim.classList.add("show");}
function closeMenu(){menu.classList.remove("open");menu.setAttribute("aria-hidden","true");scrim.classList.remove("show");}
let dragging=false,startY=0,lastY=0;menu.addEventListener("touchstart",e=>{dragging=true;startY=e.touches[0].clientY;lastY=startY;menu.classList.add("dragging");},{passive:true});menu.addEventListener("touchmove",e=>{if(!dragging)return;lastY=e.touches[0].clientY;const dy=Math.max(0,lastY-startY);menu.style.transform=`translateY(${dy}px)`;},{passive:true});menu.addEventListener("touchend",()=>{if(!dragging)return;const dy=Math.max(0,lastY-startY);dragging=false;menu.classList.remove("dragging");if(dy>120)closeMenu();menu.style.transform="";},{passive:true});
let edgeStart=null;edgeOpen.addEventListener("touchstart",e=>edgeStart=e.touches[0].clientY,{passive:true});edgeOpen.addEventListener("touchmove",e=>{if(edgeStart==null)return;const dy=e.touches[0].clientY-edgeStart;if(dy<-40){openMenu();edgeStart=null;}},{passive:true});edgeOpen.addEventListener("touchend",()=>edgeStart=null);
const chips=$("#patternChips");const customRow=$("#customRow");const customInput=$("#customPattern");const cycleStart=$("#cycleStart");const cycleOffset=$("#cycleOffset");const applyBtn=$("#applyBtn");const dots=Array.from(document.querySelectorAll("#themeDots .dot"));
const defaultState2={};cycleStart.value=state.cycleStart;cycleOffset.value=state.offset;customInput.value=(state.customPattern||[]).join(",");
chips.querySelectorAll(".chip").forEach(ch=>{if(ch.dataset.pattern===state.patternKey)ch.classList.add("active");ch.addEventListener("click",()=>{chips.querySelectorAll(".chip").forEach(c=>c.classList.remove("active"));ch.classList.add("active");state.patternKey=ch.dataset.pattern;customRow.classList.toggle("hidden",state.patternKey!=="custom");});});customRow.classList.toggle("hidden",state.patternKey!=="custom");
dots.forEach(d=>{d.classList.toggle("active",d.dataset.theme===state.themePalette);d.addEventListener("click",()=>{dots.forEach(x=>x.classList.remove("active"));d.classList.add("active");state.themePalette=d.dataset.theme;});});
applyBtn.addEventListener("click",()=>{state.cycleStart=cycleStart.value||state.cycleStart;state.offset=parseInt(cycleOffset.value||"0",10);if(state.patternKey==="custom"){const arr=customInput.value.split(/[,\s]+/).map(s=>s.trim()).filter(Boolean);state.customPattern=arr;localStorage.setItem("customPattern",JSON.stringify(arr));}
localStorage.setItem("patternKey",state.patternKey);localStorage.setItem("cycleStart",state.cycleStart);localStorage.setItem("offset",String(state.offset));localStorage.setItem("themePalette",state.themePalette);applyTheme();renderCalendar();closeMenu();});
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));}